default:
  image: golang:1.16

before_script:
  - export VERBASE=`date "+%-y.%-m%-d.%-H%-M"`

build_windows:
  variables:
    GOOS: "windows"
    GOARCH: "amd64"
  script:
    - go get github.com/cavaliercoder/grab
    - sed -i "s/{{COMMITHASH}}/${CI_COMMIT_SHA}/" main.go
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOOS-$GOARCH.exe
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}.exe" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${VERBASE}/serverinstaller-${GOOS}-${GOARCH}.exe"'


build_linux_amd64:
  variables:
    GOOS: "linux"
    GOARCH: "amd64"
  script:
    - go get github.com/cavaliercoder/grab
    - sed -i "s/{{COMMITHASH}}/${CI_COMMIT_SHA}/" main.go
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOOS-$GOARCH
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${VERBASE}/serverinstaller-${GOOS}-${GOARCH}"'


build_freebsd_amd64:
  variables:
    GOOS: "freebsd"
    GOARCH: "amd64"
  script:
    - go get github.com/cavaliercoder/grab
    - sed -i "s/{{COMMITHASH}}/${CI_COMMIT_SHA}/" main.go
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOOS-$GOARCH
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${VERBASE}/serverinstaller-${GOOS}-${GOARCH}"'


build_darwin_amd64:
  variables:
    GOOS: "darwin"
    GOARCH: "amd64"
  script:
    - go get github.com/cavaliercoder/grab
    - sed -i "s/{{COMMITHASH}}/${CI_COMMIT_SHA}/" main.go
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOOS-$GOARCH
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${VERBASE}/serverinstaller-${GOOS}-${GOARCH}"'


build_linux_arm64:
  variables:
    GOOS: "linux"
    GOARCH: "arm64"
  script:
    - go get github.com/cavaliercoder/grab
    - sed -i "s/{{COMMITHASH}}/${CI_COMMIT_SHA}/" main.go
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOOS-$GOARCH
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${VERBASE}/serverinstaller-${GOOS}-${GOARCH}"'


build_freebsd_arm64:
  variables:
    GOOS: "freebsd"
    GOARCH: "arm64"
  script:
    - go get github.com/cavaliercoder/grab
    - sed -i "s/{{COMMITHASH}}/${CI_COMMIT_SHA}/" main.go
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOOS-$GOARCH
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${VERBASE}/serverinstaller-${GOOS}-${GOARCH}"'

build_darwin_arm64:
  variables:
    GOOS: "darwin"
    GOARCH: "arm64"
  script:
    - go get github.com/cavaliercoder/grab
    - sed -i "s/{{COMMITHASH}}/${CI_COMMIT_SHA}/" main.go
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOOS-$GOARCH
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${VERBASE}/serverinstaller-${GOOS}-${GOARCH}"'
