default:
  image: golang:1.9
  before_script:
    - go get github.com/cavaliercoder/grab
    - export VERBASE=`date "+%Y%m%d%H%M"`
    - sed -i "s/{{COMMITHASH}}/${CI_COMMIT_SHA}/" main.go

stages:
  - build

build_windows:
  stage: build
  variables:
    GOOS: "windows"
    GOARCH: "amd64"
  script:
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOARCH-$GOOS.exe
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}.exe" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${CI_CIMMIT_SHA: -5}/serverinstaller-${GOOS}-${GOARCH}.exe"'


build_linux_amd64:
  stage: build
  variables:
    GOOS: "linux"
    GOARCH: "amd64"
  script:
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOOS-$GOARCH
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${CI_CIMMIT_SHA: -5}/serverinstaller-${GOOS}-${GOARCH}"'


build_freebsd_amd64:
  stage: build
  variables:
    GOOS: "freebsd"
    GOARCH: "amd64"
  script:
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOARCH-$GOOS
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${CI_CIMMIT_SHA: -5}/serverinstaller-${GOOS}-${GOARCH}"'


build_darwin_amd64:
  stage: build
  variables:
    GOOS: "darwin"
    GOARCH: "amd64"
  script:
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOARCH-$GOOS
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${CI_CIMMIT_SHA: -5}/serverinstaller-${GOOS}-${GOARCH}"'


build_linux_arm64:
  stage: build
  variables:
    GOOS: "linux"
    GOARCH: "arm64"
  script:
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOARCH-$GOOS
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${CI_CIMMIT_SHA: -5}/serverinstaller-${GOOS}-${GOARCH}"'


build_freebsd_arm64:
  stage: build
  variables:
    GOOS: "freebsd"
    GOARCH: "arm64"
  script:
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOARCH-$GOOS
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${CI_CIMMIT_SHA: -5}/serverinstaller-${GOOS}-${GOARCH}"'

build_darwin_arm64:
  stage: build
  variables:
    GOOS: "darwin"
    GOARCH: "arm64"
  script:
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - sed -i "s/{{BUILDNAME}}/${VER}/" main.go
    - go build -o $GOARCH-$GOOS
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${GOOS}-${GOARCH}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/modpacksdownloader/${CI_CIMMIT_SHA: -5}/serverinstaller-${GOOS}-${GOARCH}"'
