default:
  image: golang:1.19-alpine

before_script:
  - apk add --no-cache wget zip git
  - export VERBASE=`date "+%-y.%-m%-d.%-H%-M"`

stages:
  - build
  - package

.build:
  stage: build
  variables:
    CGO_ENABLED: 0
  script:
    - VER="${VERBASE}-${GOOS}-${GOARCH}"
    - mkdir -p ./binaries
    - go build -ldflags "-s -w -X 'main.commitStr=$CI_COMMIT_SHA' -X 'main.verStr=$VER'" -o "./binaries/$FILE_OUTPUT"
  artifacts:
    paths:
      - "./binaries/$FILE_OUTPUT"
    expire_in: 5 minutes

build_windows:
  stage: build
  extends: .build
  variables:
    GOOS: "windows"
    GOARCH: "amd64"
    FILE_OUTPUT: "windows.exe"
    
build_windows_arm64:
  stage: build
  extends: .build
  variables:
    GOOS: "windows"
    GOARCH: "arm64"
    FILE_OUTPUT: "windows-arm.exe"

build_linux_amd64:
  stage: build
  extends: .build
  variables:
    GOOS: "linux"
    GOARCH: "amd64"
    FILE_OUTPUT: "linux"

build_freebsd_amd64:
  stage: build
  extends: .build
  variables:
    GOOS: "freebsd"
    GOARCH: "amd64"
    FILE_OUTPUT: "freebsd"

build_darwin_amd64:
  stage: build
  extends: .build
  variables:
    GOOS: "darwin"
    GOARCH: "amd64"
    FILE_OUTPUT: "mac"

build_linux_arm64:
  stage: build
  extends: .build
  variables:
    GOOS: "linux"
    GOARCH: "arm64"
    FILE_OUTPUT: "linux-arm"

build_freebsd_arm64:
  stage: build
  extends: .build
  variables:
    GOOS: "freebsd"
    GOARCH: "arm64"
    FILE_OUTPUT: "freebsd-arm"

build_darwin_arm64:
  stage: build
  extends: .build
  variables:
    GOOS: "darwin"
    GOARCH: "arm64"
    FILE_OUTPUT: "mac-arm"


package:
  stage: package
  script:
    - echo "packaging everything here"
    - zip -r server-installer-$CI_COMMIT_SHORT_SHA binaries/*
#    - chmod +x upx.sh && ./upx.sh
  needs:
    - build_windows
    - build_windows_arm64
    - build_linux_amd64
    - build_freebsd_amd64
    - build_darwin_amd64
    - build_linux_arm64
    - build_freebsd_arm64
    - build_darwin_arm64
  artifacts:
    name: all-artifacts
    paths:
      - "./binaries/**"
      - "server-installer-$CI_COMMIT_SHORT_SHA.zip"
    expire_in: 1 week
